### ISSUE TITLE
[TEST] FrontEnd 테스트 코드

### ISSUE THREAD

**Issue by doitchuu** [Figci/Figci-Client#14]
## 이슈 사항
Frontend 테스트 코드를 작성하고, 테스트를 진행합니다.

<br />

## Todo 리스트

- [ ] 각 단위 별 테스트 코드를 작성합니다.
- [ ] 작성한 테스트 코드를 중심으로 테스트를 진행합니다.
- [ ] 테스트 진행 후, 테스트 결과에 따라 로직을 수정합니다.

<br />
