### ISSUE TITLE
[일반] 프로젝트 발표준비

### ISSUE THREAD

**Issue by doitchuu** [Figci/Figci-Client#17]
## 이슈 사항
웹사이트 배포 후 프로젝트 배경, 프로젝트 설명, 기술 챌린지 등 프로젝트에 대한 내용과 함께 발표를 준비합니다.

<br />

## Todo 리스트
- [ ] 코드 리뷰 및 리팩터링
전체 서비스 코드를 리뷰하면서 피드백을 통해
개선점을 파악하고 리팩터링으로 가독성을 높이기

- [ ] 서비스 시연 준비
서비스 배표 환경 체크 및 시연을 위한 플로우 선정 및 녹화

- [ ] 발표 자료 작성
팀 소개, 서비스 핵심 기능 및 발표 자료 스크립트 작성
발표 자료 PPT 작성 및 발표 내용 피드백

- [ ] 테스트와 버그 수정
테스트를 통한 안정성 확인 , 이슈 발견시 코드 수정

<br />
