### ISSUE TITLE
[FE] 비교 페이지 - 캔버스 리사이징

### ISSUE THREAD

**Issue by kyeongjun-ko** [Figci/Figci-Client#35]
## 이슈 사항
1. 캔버스 보다 큰 프레임 렌더시 스크롤을 사용해서 캔버스 비율을 조절할 수 있어야 합니다.
2. 브라우저 크기가 조정됨 에 캔버스 영역도 같은 비율로 조정 되어야 합니다.
3. 캔버스 영역은 사용자가 보는 브라우저 화면 크기의 만큼 그려져야 합니다.
4. 캔버스 영역에 그려진 프레임은 그룹화 되어서 사용자가 크기를 조절할 수 있어야 합니다.

<br />

## Todo 리스트
- [ ] Fabric canvas 객체에 캔버스 비율 확대 / 축소 스크롤 이벤트 핸들러 로직
- [ ] window 객체에 리사이징 캔버스 화면 비율 조정 이벤트 핸들러 로직
- [ ] 캔버스에 렌더될 여러개 fabric 객체들을 Group 객체로 렌더링 로직
- [ ] 프레임 노드 fabric 객체들의 저장 변수 자료구조 Object => Map 변경 

<br />
