### ISSUE TITLE
Feat: 사용자 정보(userId, profile Url) 글로벌 상태 저장

### ISSUE THREAD

**Issue by doitchuu** [Figci/Figci-Client#38]
## 이슈 사항
서버로 부터 사용자 정보를 요청하여 사용자의 아이디(`userId`)와 이미지(`profile url`)를 글로벌 상태 스토어에 저장합니다.
상태를 저장하면 저장된 상태로 비교 페이지에서 사용자의 `userId`와 `profile url`로 이미지를 노출합니다.

<br />

## Todo 리스트

- [x] 토큰을 발급받은 후, 서버에 사용자의 정보를 요청해야 합니다.
```javascript
fetch({"http://localhost:3000/user/", {
  method: "GET",
  headers: {
    authorization: accessToken
  }
});
``` 
- [x] 요청을 성공적으로 받았을 경우, 글로벌 상태로 저장해야 합니다.
- [x] 요청을 받는 데 실패했을 경우, 에러를 적절하게 핸들링해야 합니다.
- [x] 저장된 사용자 정보를 비교 페이지 화면에 노출시켜야 합니다.

<br />
